/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package wikipedia.schemas;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class RevisionWikilinks extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RevisionWikilinks\",\"namespace\":\"wikipedia.schemas\",\"fields\":[{\"name\":\"page_id\",\"type\":[\"null\",\"long\"]},{\"name\":\"revision_id\",\"type\":[\"null\",\"long\"]},{\"name\":\"timestamp\",\"type\":[\"null\",\"string\"]},{\"name\":\"wikilinks\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"string\"}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.Long page_id;
  @Deprecated public java.lang.Long revision_id;
  @Deprecated public java.lang.CharSequence timestamp;
  @Deprecated public java.util.List<java.lang.CharSequence> wikilinks;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public RevisionWikilinks() {}

  /**
   * All-args constructor.
   */
  public RevisionWikilinks(java.lang.Long page_id, java.lang.Long revision_id, java.lang.CharSequence timestamp, java.util.List<java.lang.CharSequence> wikilinks) {
    this.page_id = page_id;
    this.revision_id = revision_id;
    this.timestamp = timestamp;
    this.wikilinks = wikilinks;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return page_id;
    case 1: return revision_id;
    case 2: return timestamp;
    case 3: return wikilinks;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: page_id = (java.lang.Long)value$; break;
    case 1: revision_id = (java.lang.Long)value$; break;
    case 2: timestamp = (java.lang.CharSequence)value$; break;
    case 3: wikilinks = (java.util.List<java.lang.CharSequence>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'page_id' field.
   */
  public java.lang.Long getPageId() {
    return page_id;
  }

  /**
   * Sets the value of the 'page_id' field.
   * @param value the value to set.
   */
  public void setPageId(java.lang.Long value) {
    this.page_id = value;
  }

  /**
   * Gets the value of the 'revision_id' field.
   */
  public java.lang.Long getRevisionId() {
    return revision_id;
  }

  /**
   * Sets the value of the 'revision_id' field.
   * @param value the value to set.
   */
  public void setRevisionId(java.lang.Long value) {
    this.revision_id = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   */
  public java.lang.CharSequence getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.CharSequence value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'wikilinks' field.
   */
  public java.util.List<java.lang.CharSequence> getWikilinks() {
    return wikilinks;
  }

  /**
   * Sets the value of the 'wikilinks' field.
   * @param value the value to set.
   */
  public void setWikilinks(java.util.List<java.lang.CharSequence> value) {
    this.wikilinks = value;
  }

  /** Creates a new RevisionWikilinks RecordBuilder */
  public static wikipedia.schemas.RevisionWikilinks.Builder newBuilder() {
    return new wikipedia.schemas.RevisionWikilinks.Builder();
  }
  
  /** Creates a new RevisionWikilinks RecordBuilder by copying an existing Builder */
  public static wikipedia.schemas.RevisionWikilinks.Builder newBuilder(wikipedia.schemas.RevisionWikilinks.Builder other) {
    return new wikipedia.schemas.RevisionWikilinks.Builder(other);
  }
  
  /** Creates a new RevisionWikilinks RecordBuilder by copying an existing RevisionWikilinks instance */
  public static wikipedia.schemas.RevisionWikilinks.Builder newBuilder(wikipedia.schemas.RevisionWikilinks other) {
    return new wikipedia.schemas.RevisionWikilinks.Builder(other);
  }
  
  /**
   * RecordBuilder for RevisionWikilinks instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RevisionWikilinks>
    implements org.apache.avro.data.RecordBuilder<RevisionWikilinks> {

    private java.lang.Long page_id;
    private java.lang.Long revision_id;
    private java.lang.CharSequence timestamp;
    private java.util.List<java.lang.CharSequence> wikilinks;

    /** Creates a new Builder */
    private Builder() {
      super(wikipedia.schemas.RevisionWikilinks.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(wikipedia.schemas.RevisionWikilinks.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.page_id)) {
        this.page_id = data().deepCopy(fields()[0].schema(), other.page_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.revision_id)) {
        this.revision_id = data().deepCopy(fields()[1].schema(), other.revision_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[2].schema(), other.timestamp);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.wikilinks)) {
        this.wikilinks = data().deepCopy(fields()[3].schema(), other.wikilinks);
        fieldSetFlags()[3] = true;
      }
    }
    
    /** Creates a Builder by copying an existing RevisionWikilinks instance */
    private Builder(wikipedia.schemas.RevisionWikilinks other) {
            super(wikipedia.schemas.RevisionWikilinks.SCHEMA$);
      if (isValidValue(fields()[0], other.page_id)) {
        this.page_id = data().deepCopy(fields()[0].schema(), other.page_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.revision_id)) {
        this.revision_id = data().deepCopy(fields()[1].schema(), other.revision_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[2].schema(), other.timestamp);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.wikilinks)) {
        this.wikilinks = data().deepCopy(fields()[3].schema(), other.wikilinks);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'page_id' field */
    public java.lang.Long getPageId() {
      return page_id;
    }
    
    /** Sets the value of the 'page_id' field */
    public wikipedia.schemas.RevisionWikilinks.Builder setPageId(java.lang.Long value) {
      validate(fields()[0], value);
      this.page_id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'page_id' field has been set */
    public boolean hasPageId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'page_id' field */
    public wikipedia.schemas.RevisionWikilinks.Builder clearPageId() {
      page_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'revision_id' field */
    public java.lang.Long getRevisionId() {
      return revision_id;
    }
    
    /** Sets the value of the 'revision_id' field */
    public wikipedia.schemas.RevisionWikilinks.Builder setRevisionId(java.lang.Long value) {
      validate(fields()[1], value);
      this.revision_id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'revision_id' field has been set */
    public boolean hasRevisionId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'revision_id' field */
    public wikipedia.schemas.RevisionWikilinks.Builder clearRevisionId() {
      revision_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'timestamp' field */
    public java.lang.CharSequence getTimestamp() {
      return timestamp;
    }
    
    /** Sets the value of the 'timestamp' field */
    public wikipedia.schemas.RevisionWikilinks.Builder setTimestamp(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.timestamp = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'timestamp' field has been set */
    public boolean hasTimestamp() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'timestamp' field */
    public wikipedia.schemas.RevisionWikilinks.Builder clearTimestamp() {
      timestamp = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'wikilinks' field */
    public java.util.List<java.lang.CharSequence> getWikilinks() {
      return wikilinks;
    }
    
    /** Sets the value of the 'wikilinks' field */
    public wikipedia.schemas.RevisionWikilinks.Builder setWikilinks(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[3], value);
      this.wikilinks = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'wikilinks' field has been set */
    public boolean hasWikilinks() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'wikilinks' field */
    public wikipedia.schemas.RevisionWikilinks.Builder clearWikilinks() {
      wikilinks = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public RevisionWikilinks build() {
      try {
        RevisionWikilinks record = new RevisionWikilinks();
        record.page_id = fieldSetFlags()[0] ? this.page_id : (java.lang.Long) defaultValue(fields()[0]);
        record.revision_id = fieldSetFlags()[1] ? this.revision_id : (java.lang.Long) defaultValue(fields()[1]);
        record.timestamp = fieldSetFlags()[2] ? this.timestamp : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.wikilinks = fieldSetFlags()[3] ? this.wikilinks : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
