/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package de.mpg.mpi.inf.d5.wikipedia.export.schemas;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class CurrentPage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CurrentPage\",\"namespace\":\"de.mpg.mpi.inf.d5.wikipedia.export.schemas\",\"fields\":[{\"name\":\"page_id\",\"type\":[\"null\",\"long\"]},{\"name\":\"title\",\"type\":[\"null\",\"string\"]},{\"name\":\"redirect\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.Long page_id;
  @Deprecated public java.lang.CharSequence title;
  @Deprecated public java.lang.CharSequence redirect;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public CurrentPage() {}

  /**
   * All-args constructor.
   */
  public CurrentPage(java.lang.Long page_id, java.lang.CharSequence title, java.lang.CharSequence redirect) {
    this.page_id = page_id;
    this.title = title;
    this.redirect = redirect;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return page_id;
    case 1: return title;
    case 2: return redirect;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: page_id = (java.lang.Long)value$; break;
    case 1: title = (java.lang.CharSequence)value$; break;
    case 2: redirect = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'page_id' field.
   */
  public java.lang.Long getPageId() {
    return page_id;
  }

  /**
   * Sets the value of the 'page_id' field.
   * @param value the value to set.
   */
  public void setPageId(java.lang.Long value) {
    this.page_id = value;
  }

  /**
   * Gets the value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }

  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'redirect' field.
   */
  public java.lang.CharSequence getRedirect() {
    return redirect;
  }

  /**
   * Sets the value of the 'redirect' field.
   * @param value the value to set.
   */
  public void setRedirect(java.lang.CharSequence value) {
    this.redirect = value;
  }

  /** Creates a new CurrentPage RecordBuilder */
  public static de.mpg.mpi.inf.d5.wikipedia.export.schemas.CurrentPage.Builder newBuilder() {
    return new de.mpg.mpi.inf.d5.wikipedia.export.schemas.CurrentPage.Builder();
  }
  
  /** Creates a new CurrentPage RecordBuilder by copying an existing Builder */
  public static de.mpg.mpi.inf.d5.wikipedia.export.schemas.CurrentPage.Builder newBuilder(de.mpg.mpi.inf.d5.wikipedia.export.schemas.CurrentPage.Builder other) {
    return new de.mpg.mpi.inf.d5.wikipedia.export.schemas.CurrentPage.Builder(other);
  }
  
  /** Creates a new CurrentPage RecordBuilder by copying an existing CurrentPage instance */
  public static de.mpg.mpi.inf.d5.wikipedia.export.schemas.CurrentPage.Builder newBuilder(de.mpg.mpi.inf.d5.wikipedia.export.schemas.CurrentPage other) {
    return new de.mpg.mpi.inf.d5.wikipedia.export.schemas.CurrentPage.Builder(other);
  }
  
  /**
   * RecordBuilder for CurrentPage instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CurrentPage>
    implements org.apache.avro.data.RecordBuilder<CurrentPage> {

    private java.lang.Long page_id;
    private java.lang.CharSequence title;
    private java.lang.CharSequence redirect;

    /** Creates a new Builder */
    private Builder() {
      super(de.mpg.mpi.inf.d5.wikipedia.export.schemas.CurrentPage.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(de.mpg.mpi.inf.d5.wikipedia.export.schemas.CurrentPage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.page_id)) {
        this.page_id = data().deepCopy(fields()[0].schema(), other.page_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.redirect)) {
        this.redirect = data().deepCopy(fields()[2].schema(), other.redirect);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing CurrentPage instance */
    private Builder(de.mpg.mpi.inf.d5.wikipedia.export.schemas.CurrentPage other) {
            super(de.mpg.mpi.inf.d5.wikipedia.export.schemas.CurrentPage.SCHEMA$);
      if (isValidValue(fields()[0], other.page_id)) {
        this.page_id = data().deepCopy(fields()[0].schema(), other.page_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.redirect)) {
        this.redirect = data().deepCopy(fields()[2].schema(), other.redirect);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'page_id' field */
    public java.lang.Long getPageId() {
      return page_id;
    }
    
    /** Sets the value of the 'page_id' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.CurrentPage.Builder setPageId(java.lang.Long value) {
      validate(fields()[0], value);
      this.page_id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'page_id' field has been set */
    public boolean hasPageId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'page_id' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.CurrentPage.Builder clearPageId() {
      page_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'title' field */
    public java.lang.CharSequence getTitle() {
      return title;
    }
    
    /** Sets the value of the 'title' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.CurrentPage.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.title = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'title' field has been set */
    public boolean hasTitle() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'title' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.CurrentPage.Builder clearTitle() {
      title = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'redirect' field */
    public java.lang.CharSequence getRedirect() {
      return redirect;
    }
    
    /** Sets the value of the 'redirect' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.CurrentPage.Builder setRedirect(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.redirect = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'redirect' field has been set */
    public boolean hasRedirect() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'redirect' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.CurrentPage.Builder clearRedirect() {
      redirect = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public CurrentPage build() {
      try {
        CurrentPage record = new CurrentPage();
        record.page_id = fieldSetFlags()[0] ? this.page_id : (java.lang.Long) defaultValue(fields()[0]);
        record.title = fieldSetFlags()[1] ? this.title : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.redirect = fieldSetFlags()[2] ? this.redirect : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
