/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package de.mpg.mpi.inf.d5.wikipedia.export.schemas;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class RevisionMetadata extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RevisionMetadata\",\"namespace\":\"de.mpg.mpi.inf.d5.wikipedia.export.schemas\",\"fields\":[{\"name\":\"page_id\",\"type\":[\"null\",\"long\"]},{\"name\":\"revision_id\",\"type\":[\"null\",\"long\"]},{\"name\":\"parent_id\",\"type\":[\"null\",\"long\"]},{\"name\":\"timestamp\",\"type\":[\"null\",\"string\"]},{\"name\":\"contributor_ip\",\"type\":[\"null\",\"string\"]},{\"name\":\"contributor_user_id\",\"type\":[\"null\",\"long\"]},{\"name\":\"contributor_username\",\"type\":[\"null\",\"string\"]},{\"name\":\"minor\",\"type\":[\"null\",\"boolean\"]},{\"name\":\"comment\",\"type\":[\"null\",\"string\"]},{\"name\":\"model\",\"type\":[\"null\",\"string\"]},{\"name\":\"format\",\"type\":[\"null\",\"string\"]},{\"name\":\"text_size\",\"type\":[\"null\",\"int\"]},{\"name\":\"sha1\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.Long page_id;
  @Deprecated public java.lang.Long revision_id;
  @Deprecated public java.lang.Long parent_id;
  @Deprecated public java.lang.CharSequence timestamp;
  @Deprecated public java.lang.CharSequence contributor_ip;
  @Deprecated public java.lang.Long contributor_user_id;
  @Deprecated public java.lang.CharSequence contributor_username;
  @Deprecated public java.lang.Boolean minor;
  @Deprecated public java.lang.CharSequence comment;
  @Deprecated public java.lang.CharSequence model;
  @Deprecated public java.lang.CharSequence format;
  @Deprecated public java.lang.Integer text_size;
  @Deprecated public java.lang.CharSequence sha1;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public RevisionMetadata() {}

  /**
   * All-args constructor.
   */
  public RevisionMetadata(java.lang.Long page_id, java.lang.Long revision_id, java.lang.Long parent_id, java.lang.CharSequence timestamp, java.lang.CharSequence contributor_ip, java.lang.Long contributor_user_id, java.lang.CharSequence contributor_username, java.lang.Boolean minor, java.lang.CharSequence comment, java.lang.CharSequence model, java.lang.CharSequence format, java.lang.Integer text_size, java.lang.CharSequence sha1) {
    this.page_id = page_id;
    this.revision_id = revision_id;
    this.parent_id = parent_id;
    this.timestamp = timestamp;
    this.contributor_ip = contributor_ip;
    this.contributor_user_id = contributor_user_id;
    this.contributor_username = contributor_username;
    this.minor = minor;
    this.comment = comment;
    this.model = model;
    this.format = format;
    this.text_size = text_size;
    this.sha1 = sha1;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return page_id;
    case 1: return revision_id;
    case 2: return parent_id;
    case 3: return timestamp;
    case 4: return contributor_ip;
    case 5: return contributor_user_id;
    case 6: return contributor_username;
    case 7: return minor;
    case 8: return comment;
    case 9: return model;
    case 10: return format;
    case 11: return text_size;
    case 12: return sha1;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: page_id = (java.lang.Long)value$; break;
    case 1: revision_id = (java.lang.Long)value$; break;
    case 2: parent_id = (java.lang.Long)value$; break;
    case 3: timestamp = (java.lang.CharSequence)value$; break;
    case 4: contributor_ip = (java.lang.CharSequence)value$; break;
    case 5: contributor_user_id = (java.lang.Long)value$; break;
    case 6: contributor_username = (java.lang.CharSequence)value$; break;
    case 7: minor = (java.lang.Boolean)value$; break;
    case 8: comment = (java.lang.CharSequence)value$; break;
    case 9: model = (java.lang.CharSequence)value$; break;
    case 10: format = (java.lang.CharSequence)value$; break;
    case 11: text_size = (java.lang.Integer)value$; break;
    case 12: sha1 = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'page_id' field.
   */
  public java.lang.Long getPageId() {
    return page_id;
  }

  /**
   * Sets the value of the 'page_id' field.
   * @param value the value to set.
   */
  public void setPageId(java.lang.Long value) {
    this.page_id = value;
  }

  /**
   * Gets the value of the 'revision_id' field.
   */
  public java.lang.Long getRevisionId() {
    return revision_id;
  }

  /**
   * Sets the value of the 'revision_id' field.
   * @param value the value to set.
   */
  public void setRevisionId(java.lang.Long value) {
    this.revision_id = value;
  }

  /**
   * Gets the value of the 'parent_id' field.
   */
  public java.lang.Long getParentId() {
    return parent_id;
  }

  /**
   * Sets the value of the 'parent_id' field.
   * @param value the value to set.
   */
  public void setParentId(java.lang.Long value) {
    this.parent_id = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   */
  public java.lang.CharSequence getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.CharSequence value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'contributor_ip' field.
   */
  public java.lang.CharSequence getContributorIp() {
    return contributor_ip;
  }

  /**
   * Sets the value of the 'contributor_ip' field.
   * @param value the value to set.
   */
  public void setContributorIp(java.lang.CharSequence value) {
    this.contributor_ip = value;
  }

  /**
   * Gets the value of the 'contributor_user_id' field.
   */
  public java.lang.Long getContributorUserId() {
    return contributor_user_id;
  }

  /**
   * Sets the value of the 'contributor_user_id' field.
   * @param value the value to set.
   */
  public void setContributorUserId(java.lang.Long value) {
    this.contributor_user_id = value;
  }

  /**
   * Gets the value of the 'contributor_username' field.
   */
  public java.lang.CharSequence getContributorUsername() {
    return contributor_username;
  }

  /**
   * Sets the value of the 'contributor_username' field.
   * @param value the value to set.
   */
  public void setContributorUsername(java.lang.CharSequence value) {
    this.contributor_username = value;
  }

  /**
   * Gets the value of the 'minor' field.
   */
  public java.lang.Boolean getMinor() {
    return minor;
  }

  /**
   * Sets the value of the 'minor' field.
   * @param value the value to set.
   */
  public void setMinor(java.lang.Boolean value) {
    this.minor = value;
  }

  /**
   * Gets the value of the 'comment' field.
   */
  public java.lang.CharSequence getComment() {
    return comment;
  }

  /**
   * Sets the value of the 'comment' field.
   * @param value the value to set.
   */
  public void setComment(java.lang.CharSequence value) {
    this.comment = value;
  }

  /**
   * Gets the value of the 'model' field.
   */
  public java.lang.CharSequence getModel() {
    return model;
  }

  /**
   * Sets the value of the 'model' field.
   * @param value the value to set.
   */
  public void setModel(java.lang.CharSequence value) {
    this.model = value;
  }

  /**
   * Gets the value of the 'format' field.
   */
  public java.lang.CharSequence getFormat() {
    return format;
  }

  /**
   * Sets the value of the 'format' field.
   * @param value the value to set.
   */
  public void setFormat(java.lang.CharSequence value) {
    this.format = value;
  }

  /**
   * Gets the value of the 'text_size' field.
   */
  public java.lang.Integer getTextSize() {
    return text_size;
  }

  /**
   * Sets the value of the 'text_size' field.
   * @param value the value to set.
   */
  public void setTextSize(java.lang.Integer value) {
    this.text_size = value;
  }

  /**
   * Gets the value of the 'sha1' field.
   */
  public java.lang.CharSequence getSha1() {
    return sha1;
  }

  /**
   * Sets the value of the 'sha1' field.
   * @param value the value to set.
   */
  public void setSha1(java.lang.CharSequence value) {
    this.sha1 = value;
  }

  /** Creates a new RevisionMetadata RecordBuilder */
  public static de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder newBuilder() {
    return new de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder();
  }
  
  /** Creates a new RevisionMetadata RecordBuilder by copying an existing Builder */
  public static de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder newBuilder(de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder other) {
    return new de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder(other);
  }
  
  /** Creates a new RevisionMetadata RecordBuilder by copying an existing RevisionMetadata instance */
  public static de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder newBuilder(de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata other) {
    return new de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder(other);
  }
  
  /**
   * RecordBuilder for RevisionMetadata instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RevisionMetadata>
    implements org.apache.avro.data.RecordBuilder<RevisionMetadata> {

    private java.lang.Long page_id;
    private java.lang.Long revision_id;
    private java.lang.Long parent_id;
    private java.lang.CharSequence timestamp;
    private java.lang.CharSequence contributor_ip;
    private java.lang.Long contributor_user_id;
    private java.lang.CharSequence contributor_username;
    private java.lang.Boolean minor;
    private java.lang.CharSequence comment;
    private java.lang.CharSequence model;
    private java.lang.CharSequence format;
    private java.lang.Integer text_size;
    private java.lang.CharSequence sha1;

    /** Creates a new Builder */
    private Builder() {
      super(de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.page_id)) {
        this.page_id = data().deepCopy(fields()[0].schema(), other.page_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.revision_id)) {
        this.revision_id = data().deepCopy(fields()[1].schema(), other.revision_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.parent_id)) {
        this.parent_id = data().deepCopy(fields()[2].schema(), other.parent_id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[3].schema(), other.timestamp);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.contributor_ip)) {
        this.contributor_ip = data().deepCopy(fields()[4].schema(), other.contributor_ip);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.contributor_user_id)) {
        this.contributor_user_id = data().deepCopy(fields()[5].schema(), other.contributor_user_id);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.contributor_username)) {
        this.contributor_username = data().deepCopy(fields()[6].schema(), other.contributor_username);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.minor)) {
        this.minor = data().deepCopy(fields()[7].schema(), other.minor);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.comment)) {
        this.comment = data().deepCopy(fields()[8].schema(), other.comment);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.model)) {
        this.model = data().deepCopy(fields()[9].schema(), other.model);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.format)) {
        this.format = data().deepCopy(fields()[10].schema(), other.format);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.text_size)) {
        this.text_size = data().deepCopy(fields()[11].schema(), other.text_size);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.sha1)) {
        this.sha1 = data().deepCopy(fields()[12].schema(), other.sha1);
        fieldSetFlags()[12] = true;
      }
    }
    
    /** Creates a Builder by copying an existing RevisionMetadata instance */
    private Builder(de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata other) {
            super(de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.SCHEMA$);
      if (isValidValue(fields()[0], other.page_id)) {
        this.page_id = data().deepCopy(fields()[0].schema(), other.page_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.revision_id)) {
        this.revision_id = data().deepCopy(fields()[1].schema(), other.revision_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.parent_id)) {
        this.parent_id = data().deepCopy(fields()[2].schema(), other.parent_id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[3].schema(), other.timestamp);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.contributor_ip)) {
        this.contributor_ip = data().deepCopy(fields()[4].schema(), other.contributor_ip);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.contributor_user_id)) {
        this.contributor_user_id = data().deepCopy(fields()[5].schema(), other.contributor_user_id);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.contributor_username)) {
        this.contributor_username = data().deepCopy(fields()[6].schema(), other.contributor_username);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.minor)) {
        this.minor = data().deepCopy(fields()[7].schema(), other.minor);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.comment)) {
        this.comment = data().deepCopy(fields()[8].schema(), other.comment);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.model)) {
        this.model = data().deepCopy(fields()[9].schema(), other.model);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.format)) {
        this.format = data().deepCopy(fields()[10].schema(), other.format);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.text_size)) {
        this.text_size = data().deepCopy(fields()[11].schema(), other.text_size);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.sha1)) {
        this.sha1 = data().deepCopy(fields()[12].schema(), other.sha1);
        fieldSetFlags()[12] = true;
      }
    }

    /** Gets the value of the 'page_id' field */
    public java.lang.Long getPageId() {
      return page_id;
    }
    
    /** Sets the value of the 'page_id' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder setPageId(java.lang.Long value) {
      validate(fields()[0], value);
      this.page_id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'page_id' field has been set */
    public boolean hasPageId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'page_id' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder clearPageId() {
      page_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'revision_id' field */
    public java.lang.Long getRevisionId() {
      return revision_id;
    }
    
    /** Sets the value of the 'revision_id' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder setRevisionId(java.lang.Long value) {
      validate(fields()[1], value);
      this.revision_id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'revision_id' field has been set */
    public boolean hasRevisionId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'revision_id' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder clearRevisionId() {
      revision_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'parent_id' field */
    public java.lang.Long getParentId() {
      return parent_id;
    }
    
    /** Sets the value of the 'parent_id' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder setParentId(java.lang.Long value) {
      validate(fields()[2], value);
      this.parent_id = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'parent_id' field has been set */
    public boolean hasParentId() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'parent_id' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder clearParentId() {
      parent_id = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'timestamp' field */
    public java.lang.CharSequence getTimestamp() {
      return timestamp;
    }
    
    /** Sets the value of the 'timestamp' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder setTimestamp(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.timestamp = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'timestamp' field has been set */
    public boolean hasTimestamp() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'timestamp' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder clearTimestamp() {
      timestamp = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'contributor_ip' field */
    public java.lang.CharSequence getContributorIp() {
      return contributor_ip;
    }
    
    /** Sets the value of the 'contributor_ip' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder setContributorIp(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.contributor_ip = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'contributor_ip' field has been set */
    public boolean hasContributorIp() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'contributor_ip' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder clearContributorIp() {
      contributor_ip = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'contributor_user_id' field */
    public java.lang.Long getContributorUserId() {
      return contributor_user_id;
    }
    
    /** Sets the value of the 'contributor_user_id' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder setContributorUserId(java.lang.Long value) {
      validate(fields()[5], value);
      this.contributor_user_id = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'contributor_user_id' field has been set */
    public boolean hasContributorUserId() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'contributor_user_id' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder clearContributorUserId() {
      contributor_user_id = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'contributor_username' field */
    public java.lang.CharSequence getContributorUsername() {
      return contributor_username;
    }
    
    /** Sets the value of the 'contributor_username' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder setContributorUsername(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.contributor_username = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'contributor_username' field has been set */
    public boolean hasContributorUsername() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'contributor_username' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder clearContributorUsername() {
      contributor_username = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'minor' field */
    public java.lang.Boolean getMinor() {
      return minor;
    }
    
    /** Sets the value of the 'minor' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder setMinor(java.lang.Boolean value) {
      validate(fields()[7], value);
      this.minor = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'minor' field has been set */
    public boolean hasMinor() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'minor' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder clearMinor() {
      minor = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'comment' field */
    public java.lang.CharSequence getComment() {
      return comment;
    }
    
    /** Sets the value of the 'comment' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder setComment(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.comment = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'comment' field has been set */
    public boolean hasComment() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'comment' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder clearComment() {
      comment = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'model' field */
    public java.lang.CharSequence getModel() {
      return model;
    }
    
    /** Sets the value of the 'model' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder setModel(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.model = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'model' field has been set */
    public boolean hasModel() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'model' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder clearModel() {
      model = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'format' field */
    public java.lang.CharSequence getFormat() {
      return format;
    }
    
    /** Sets the value of the 'format' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder setFormat(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.format = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'format' field has been set */
    public boolean hasFormat() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'format' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder clearFormat() {
      format = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'text_size' field */
    public java.lang.Integer getTextSize() {
      return text_size;
    }
    
    /** Sets the value of the 'text_size' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder setTextSize(java.lang.Integer value) {
      validate(fields()[11], value);
      this.text_size = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'text_size' field has been set */
    public boolean hasTextSize() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'text_size' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder clearTextSize() {
      text_size = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'sha1' field */
    public java.lang.CharSequence getSha1() {
      return sha1;
    }
    
    /** Sets the value of the 'sha1' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder setSha1(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.sha1 = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'sha1' field has been set */
    public boolean hasSha1() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'sha1' field */
    public de.mpg.mpi.inf.d5.wikipedia.export.schemas.RevisionMetadata.Builder clearSha1() {
      sha1 = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    @Override
    public RevisionMetadata build() {
      try {
        RevisionMetadata record = new RevisionMetadata();
        record.page_id = fieldSetFlags()[0] ? this.page_id : (java.lang.Long) defaultValue(fields()[0]);
        record.revision_id = fieldSetFlags()[1] ? this.revision_id : (java.lang.Long) defaultValue(fields()[1]);
        record.parent_id = fieldSetFlags()[2] ? this.parent_id : (java.lang.Long) defaultValue(fields()[2]);
        record.timestamp = fieldSetFlags()[3] ? this.timestamp : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.contributor_ip = fieldSetFlags()[4] ? this.contributor_ip : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.contributor_user_id = fieldSetFlags()[5] ? this.contributor_user_id : (java.lang.Long) defaultValue(fields()[5]);
        record.contributor_username = fieldSetFlags()[6] ? this.contributor_username : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.minor = fieldSetFlags()[7] ? this.minor : (java.lang.Boolean) defaultValue(fields()[7]);
        record.comment = fieldSetFlags()[8] ? this.comment : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.model = fieldSetFlags()[9] ? this.model : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.format = fieldSetFlags()[10] ? this.format : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.text_size = fieldSetFlags()[11] ? this.text_size : (java.lang.Integer) defaultValue(fields()[11]);
        record.sha1 = fieldSetFlags()[12] ? this.sha1 : (java.lang.CharSequence) defaultValue(fields()[12]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
